export const UI_TEXT_CONTRACT = [
  { id: "UI-001", english: "FH6 Goliath Coach", text: "FH6 Goliath Coach", decision: "keep_english" },
  { id: "UI-002", english: "1 m sampled driving path, not verified road geometry.", text: "1 m間隔でサンプリングした走行パスです。検証済みの道路形状ではありません。", decision: "translate" },
  { id: "UI-003", english: "3D", text: "3D", decision: "keep_english" },
  { id: "UI-004", english: "2D", text: "2D", decision: "keep_english" },
  { id: "UI-005", english: "Reset camera", text: "カメラをリセット", decision: "translate" },
  { id: "UI-006", english: "Map orientation", text: "マップの向き", decision: "translate" },
  { id: "UI-007", english: "+X -> right", text: "+X -> right", decision: "translate" },
  { id: "UI-008", english: "+Z -> map up", text: "+Z -> map up", decision: "translate" },
  { id: "UI-009", english: "Elevation scale", text: "高さ倍率", decision: "translate" },
  { id: "UI-010", english: "Elevation context", text: "高度ガイド", decision: "translate" },
  { id: "UI-011", english: "Relative Elevation", text: "相対高度", decision: "translate" },
  { id: "UI-012", english: "Datum", text: "基準", decision: "translate" },
  { id: "UI-013", english: "Course minimum = 0 m", text: "コース最低地点 = 0 m", decision: "translate" },
  { id: "UI-014", english: "Start", text: "開始地点", decision: "translate" },
  { id: "UI-015", english: "Finish", text: "終了地点", decision: "translate" },
  { id: "UI-016", english: "Maximum", text: "最高地点", decision: "translate" },
  { id: "UI-017", english: "Range", text: "高低差", decision: "translate" },
  { id: "UI-018", english: "Minimum at", text: "最低地点", decision: "translate" },
  { id: "UI-019", english: "Maximum at", text: "最高地点", decision: "translate" },
  { id: "UI-020", english: "Visual", text: "表示倍率", decision: "translate" },
  { id: "UI-021", english: "Local Sessions", text: "ローカルセッション", decision: "translate" },
  { id: "UI-022", english: "Selecting a session does not replace the loaded telemetry.", text: "セッションを選択しただけでは、現在読込まれている走行データは切り替わりません。", decision: "translate" },
  { id: "UI-023", english: "Refresh", text: "更新", decision: "translate" },
  { id: "UI-024", english: "Refreshing...", text: "更新中...", decision: "translate" },
  { id: "UI-025", english: "Show ignored", text: "除外済みも表示", decision: "translate" },
  { id: "UI-026", english: "Clear", text: "表示を消去", decision: "translate" },
  { id: "UI-027", english: "Local telemetry sessions", text: "ローカル走行セッション", decision: "translate" },
  { id: "UI-028", english: "No local sessions found.", text: "ローカルセッションが見つかりません。", decision: "translate" },
  { id: "UI-029", english: "Found {count} local session(s).", text: "ローカルセッションが{count}件見つかりました。", decision: "translate" },
  { id: "UI-030", english: "Local session service unavailable.", text: "ローカルセッションサービスを利用できません。", decision: "translate" },
  { id: "UI-031", english: "Loading projected lap...", text: "走行データを読込中...", decision: "translate" },
  { id: "UI-032", english: "Loaded {sessionId}.", text: "{sessionId}を読込みました。", decision: "translate" },
  { id: "UI-033", english: "Failed to load processed projected lap.", text: "処理済み走行データの読込みに失敗しました。", decision: "translate" },
  { id: "UI-034", english: "Processing...", text: "処理中...", decision: "translate" },
  { id: "UI-035", english: "Failed to process selected session.", text: "選択したセッションの処理に失敗しました。", decision: "translate" },
  { id: "UI-036", english: "Unknown vehicle", text: "車両不明", decision: "translate" },
  { id: "UI-037", english: "packets", text: "パケット", decision: "translate" },
  { id: "UI-038", english: "Process & Load", text: "処理と読込", decision: "translate" },
  { id: "UI-039", english: "Load", text: "読込", decision: "translate" },
  { id: "UI-040", english: "Loading...", text: "読込中...", decision: "translate" },
  { id: "UI-041", english: "Processed output is ready for browser loading.", text: "処理済みデータをブラウザへ読込めます。", decision: "translate" },
  { id: "UI-042", english: "This completed local session can be processed and loaded.", text: "この完了済みセッションは処理して読込めます。", decision: "translate" },
  { id: "UI-043", english: "Partial processed output needs CLI inspection before loading.", text: "部分的な処理結果です。読込む前にCLIでの確認が必要です。", decision: "translate" },
  { id: "UI-044", english: "Ignored sessions are not processed from the browser.", text: "除外済みセッションはブラウザから処理できません。", decision: "translate" },
  { id: "UI-045", english: "Incomplete recordings cannot be processed yet.", text: "未完了の記録はまだ処理できません。", decision: "translate" },
  { id: "UI-046", english: "Invalid session source files.", text: "セッションの入力ファイルが無効です。", decision: "translate" },
  { id: "UI-047", english: "No browser action is available for this session.", text: "このセッションに対してブラウザから実行できる操作はありません。", decision: "translate" },
  { id: "UI-048", english: "Unknown start", text: "開始時刻不明", decision: "translate" },
  { id: "UI-049", english: "Unknown duration", text: "記録時間不明", decision: "translate" },
  { id: "UI-050", english: "completed", text: "完了", decision: "translate" },
  { id: "UI-051", english: "legacy-ready", text: "旧形式・処理可能", decision: "translate" },
  { id: "UI-052", english: "incomplete", text: "未完了", decision: "translate" },
  { id: "UI-053", english: "invalid", text: "無効", decision: "translate" },
  { id: "UI-054", english: "processed", text: "処理済み", decision: "translate" },
  { id: "UI-055", english: "unprocessed", text: "未処理", decision: "translate" },
  { id: "UI-056", english: "partial", text: "部分出力", decision: "translate" },
  { id: "UI-057", english: "ignored", text: "除外済み", decision: "translate" },
  { id: "UI-058", english: "loaded", text: "読込中", decision: "translate" },
  { id: "UI-059", english: "Telemetry Overlay", text: "走行ライン表示", decision: "translate" },
  { id: "UI-060", english: "Load a processed projected-lap CSV manually.", text: "処理済みのprojected-lap CSVを手動で読込みます。", decision: "translate" },
  { id: "UI-061", english: "Load CSV manually", text: "CSVを手動読込", decision: "translate" },
  { id: "UI-062", english: "Reference", text: "基準ライン", decision: "translate" },
  { id: "UI-063", english: "Actual", text: "実走ライン", decision: "translate" },
  { id: "UI-064", english: "Rewinds", text: "巻き戻し", decision: "translate" },
  { id: "UI-065", english: "Vehicle", text: "車両", decision: "translate" },
  { id: "UI-066", english: "Session", text: "セッション", decision: "translate" },
  { id: "UI-067", english: "File", text: "ファイル", decision: "translate" },
  { id: "UI-068", english: "Lap time", text: "ラップタイム", decision: "translate" },
  { id: "UI-069", english: "Markers", text: "マーカー", decision: "translate" },
  { id: "UI-070", english: "Unknown", text: "不明", decision: "translate" },
  { id: "UI-071", english: "No projected lap loaded.", text: "走行データが読込まれていません。", decision: "translate" },
  { id: "UI-072", english: "Telemetry Charts", text: "テレメトリーチャート", decision: "translate" },
  { id: "UI-073", english: "Load a processed lap to view telemetry charts.", text: "処理済み走行データを読込むとチャートを表示できます。", decision: "translate" },
  { id: "UI-074", english: "Unknown session", text: "セッション不明", decision: "translate" },
  { id: "UI-075", english: "Telemetry chart range", text: "チャート表示範囲", decision: "translate" },
  { id: "UI-076", english: "Full lap", text: "全周", decision: "translate" },
  { id: "UI-077", english: "Selected section", text: "選択セクション", decision: "translate" },
  { id: "UI-078", english: "Clear cursor", text: "カーソルを解除", decision: "translate" },
  { id: "UI-079", english: "Move over a chart to inspect distance, section, lap time, and channel values.", text: "チャート上にポインターを移動すると、距離、セクション、ラップタイム、各値を確認できます。", decision: "translate" },
  { id: "UI-080", english: "Effective driving trace uses non-superseded samples. Rewind markers remain event markers. Decimation is display-only and preserves extrema.", text: "有効走行ラインには置換されていないサンプルを使用します。巻き戻しはイベントマーカーとして残ります。間引きは表示専用で、極値を保持します。", decision: "translate" },
  { id: "UI-081", english: "Distance", text: "距離", decision: "translate" },
  { id: "UI-082", english: "Section", text: "セクション", decision: "translate" },
  { id: "UI-083", english: "Lap time", text: "ラップタイム", decision: "translate" },
  { id: "UI-084", english: "Speed", text: "Speed", decision: "keep_english" },
  { id: "UI-085", english: "Throttle", text: "Throttle", decision: "keep_english" },
  { id: "UI-086", english: "Brake", text: "Brake", decision: "keep_english" },
  { id: "UI-087", english: "Steering", text: "Steering", decision: "keep_english" },
  { id: "UI-088", english: "visible", text: "表示対象", decision: "translate" },
  { id: "UI-089", english: "drawn", text: "描画", decision: "translate" },
  { id: "UI-090", english: "Unavailable", text: "利用不可", decision: "translate" },
  { id: "UI-091", english: "Not available - reprocess the session.", text: "利用できません。セッションを再処理してください。", decision: "translate" },
  { id: "UI-092", english: "External", text: "外的要因", decision: "translate" },
  { id: "UI-093", english: "Driving", text: "運転ミス", decision: "translate" },
  { id: "UI-094", english: "Unclear", text: "不明", decision: "translate" },
  { id: "UI-095", english: "External impact suspected is a cautious inference from abrupt impulses or speed changes. It does not identify AI cars, walls, or terrain.", text: "外的衝突の疑いは、急激な入力や速度変化から慎重に推定したものです。AI車、壁、地形のいずれかを特定するものではありません。", decision: "translate" },
  { id: "UI-096", english: "Events", text: "イベント数", decision: "translate" },
  { id: "UI-097", english: "Class", text: "分類", decision: "translate" },
  { id: "UI-098", english: "Confidence", text: "信頼度", decision: "translate" },
  { id: "UI-099", english: "Rewound", text: "巻き戻し量", decision: "translate" },
  { id: "UI-100", english: "Direction", text: "方向", decision: "translate" },
  { id: "UI-101", english: "Rewind events", text: "巻き戻しイベント", decision: "translate" },
  { id: "UI-102", english: "Clear rewind selection", text: "巻き戻し選択を解除", decision: "translate" },
  { id: "UI-103", english: "Practice focus", text: "重点練習箇所", decision: "translate" },
  { id: "UI-104", english: "No high-confidence practice focus identified.", text: "信頼度の高い重点練習箇所は見つかりませんでした。", decision: "translate" },
  { id: "UI-105", english: "low", text: "低", decision: "translate" },
  { id: "UI-106", english: "unknown", text: "不明", decision: "translate" },
  { id: "UI-107", english: "Sections", text: "セクション", decision: "translate" },
  { id: "UI-108", english: "End", text: "終了地点", decision: "translate" },
  { id: "UI-109", english: "Length", text: "区間距離", decision: "translate" },
  { id: "UI-110", english: "Actual time", text: "実走タイム", decision: "translate" },
  { id: "UI-111", english: "Vehicle & Tune", text: "車両・チューニング", decision: "translate" },
  { id: "UI-112", english: "Minimal vehicle specs. Engine details beyond notes stay free-text.", text: "必要最小限の車両情報です。エンジンの詳細はメモ欄へ自由入力します。", decision: "translate" },
  { id: "UI-113", english: "Save JSON", text: "JSONを保存", decision: "translate" },
  { id: "UI-114", english: "Load JSON", text: "JSONを読込む", decision: "translate" },
  { id: "UI-115", english: "Ready", text: "準備完了", decision: "translate" },
  { id: "UI-116", english: "JSON saved", text: "JSONを保存しました", decision: "translate" },
  { id: "UI-117", english: "Loaded {fileName}", text: "{fileName}を読込みました", decision: "translate" },
  { id: "UI-118", english: "Could not load JSON", text: "JSONを読込めませんでした", decision: "translate" },
  { id: "UI-119", english: "Vehicle", text: "車両", decision: "translate" },
  { id: "UI-120", english: "Vehicle name", text: "車両名", decision: "translate" },
  { id: "UI-121", english: "Year", text: "年式", decision: "translate" },
  { id: "UI-122", english: "Class", text: "クラス", decision: "translate" },
  { id: "UI-123", english: "PI", text: "PI", decision: "keep_english" },
  { id: "UI-124", english: "Drivetrain", text: "駆動方式", decision: "translate" },
  { id: "UI-125", english: "FWD", text: "FWD", decision: "keep_english" },
  { id: "UI-126", english: "RWD", text: "RWD", decision: "keep_english" },
  { id: "UI-127", english: "AWD", text: "AWD", decision: "keep_english" },
  { id: "UI-128", english: "Power", text: "出力", decision: "translate" },
  { id: "UI-129", english: "Torque", text: "トルク", decision: "translate" },
  { id: "UI-130", english: "Weight", text: "重量", decision: "translate" },
  { id: "UI-131", english: "Front weight", text: "前輪荷重配分", decision: "translate" },
  { id: "UI-132", english: "Engine notes", text: "エンジンメモ", decision: "translate" },
  { id: "UI-133", english: "1. Tires", text: "1. タイヤ空気圧", decision: "translate" },
  { id: "UI-134", english: "Front pressure", text: "フロント", decision: "translate" },
  { id: "UI-135", english: "Rear pressure", text: "リア", decision: "translate" },
  { id: "UI-136", english: "2. Gearing", text: "2. ギア", decision: "translate" },
  { id: "UI-137", english: "Final drive", text: "ファイナルドライブ", decision: "translate" },
  { id: "UI-138", english: "3. Alignment", text: "3. アライメント", decision: "translate" },
  { id: "UI-139", english: "Front camber", text: "フロント", decision: "translate" },
  { id: "UI-140", english: "Rear camber", text: "リア", decision: "translate" },
  { id: "UI-141", english: "Front toe", text: "フロントトー", decision: "translate" },
  { id: "UI-142", english: "Rear toe", text: "リアトー", decision: "translate" },
  { id: "UI-143", english: "Front caster", text: "フロントキャスター", decision: "translate" },
  { id: "UI-144", english: "4. Anti-roll bars", text: "4. スタビライザー", decision: "translate" },
  { id: "UI-145", english: "5. Springs", text: "5. スプリング", decision: "translate" },
  { id: "UI-146", english: "6. Ride height", text: "6. 車高", decision: "translate" },
  { id: "UI-147", english: "7. Damping", text: "7. ダンピング", decision: "translate" },
  { id: "UI-148", english: "Front rebound", text: "フロント減衰力", decision: "translate" },
  { id: "UI-149", english: "Rear rebound", text: "リア減衰力", decision: "translate" },
  { id: "UI-150", english: "Front bump", text: "フロントバンプ", decision: "translate" },
  { id: "UI-151", english: "Rear bump", text: "リアバンプ", decision: "translate" },
  { id: "UI-152", english: "8. Aero", text: "8. エアロ", decision: "translate" },
  { id: "UI-153", english: "9. Brakes", text: "9. ブレーキ", decision: "translate" },
  { id: "UI-154", english: "Balance", text: "バランス", decision: "translate" },
  { id: "UI-155", english: "Pressure", text: "圧力", decision: "translate" },
  { id: "UI-156", english: "10. Differential", text: "10. デファレンシャル", decision: "translate" },
  { id: "UI-157", english: "Front accel", text: "フロント加速", decision: "translate" },
  { id: "UI-158", english: "Front decel", text: "フロント減速", decision: "translate" },
  { id: "UI-159", english: "Rear accel", text: "リア加速", decision: "translate" },
  { id: "UI-160", english: "Rear decel", text: "リア減速", decision: "translate" },
  { id: "UI-161", english: "Center balance", text: "センターバランス", decision: "translate" },
] as const;

export const KEEP_ENGLISH_TEXTS = [
  "FH6 Goliath Coach",
  "3D",
  "2D",
  "Speed",
  "Throttle",
  "Brake",
  "Steering",
  "PI",
  "FWD",
  "RWD",
  "AWD",
] as const;

export const UI_TEXT = {
  appName: "FH6 Goliath Coach",
  appDescription: "1 m間隔でサンプリングした走行パスです。検証済みの道路形状ではありません。",
  loadingReference: "Goliath基準パスを読込中...",
  referenceLoadFailed: "基準データの読込みに失敗しました。",
  view3d: "3D",
  view2d: "2D",
  mapDisplayMode: "マップ表示モード",
  overview: "全体表示",
  sectionFocus: "セクションフォーカス",
  resetCamera: "カメラをリセット",
  mapOrientation: "マップの向き",
  xRight: "+X -> right",
  zMapUp: "+Z -> map up",
  elevationScale: "高さ倍率",
  elevationContext: "高度ガイド",
  relativeElevation: "相対高度",
  datum: "基準",
  courseMinimum: "コース最低地点 = 0 m",
  start: "開始地点",
  finish: "終了地点",
  maximum: "最高地点",
  range: "高低差",
  minimumAt: "最低地点",
  maximumAt: "最高地点",
  visual: "表示倍率",
  telemetryOverlay: "走行ライン表示",
  manualCsvDescription: "処理済みのprojected-lap CSVを手動で読込みます。",
  loadCsvManually: "CSVを手動読込",
  reference: "基準ライン",
  actual: "実走ライン",
  rewinds: "巻き戻し",
  vehicle: "車両",
  session: "セッション",
  file: "ファイル",
  lapTime: "ラップタイム",
  markers: "マーカー",
  unknown: "不明",
  noProjectedLap: "走行データが読込まれていません。",
  failedProjectedLap: "走行データを読込めませんでした。",
  external: "外的要因",
  driving: "運転ミス",
  unclear: "不明",
  rewindCaution: "外的衝突の疑いは、急激な入力や速度変化から慎重に推定したものです。AI車、壁、地形のいずれかを特定するものではありません。",
  distance: "距離",
  events: "イベント数",
  class: "分類",
  confidence: "信頼度",
  rewound: "巻き戻し量",
  direction: "方向",
  rewindEvents: "巻き戻しイベント",
  clearRewindSelection: "巻き戻し選択を解除",
  practiceFocus: "重点練習箇所",
  noPracticeFocus: "信頼度の高い重点練習箇所は見つかりませんでした。",
  low: "低",
  sections: "セクション",
  end: "終了地点",
  length: "区間距離",
  actualTime: "実走タイム",
} as const;

export const uiText = {
  foundLocalSessions: (count: number) => `ローカルセッションが${count}件見つかりました。`,
  loadedSession: (sessionId: string) => `${sessionId}を読込みました。`,
  loadedJson: (fileName: string) => `${fileName}を読込みました`,
  visibleDrawnSamples: (visible: number, drawn: number) =>
    `${visible.toLocaleString()} 表示対象サンプル; ${drawn.toLocaleString()} 描画。`,
  visibleSampleCount: (count: number) => `${count.toLocaleString()} 表示対象`,
  drawnSampleCount: (count: number) => `${count.toLocaleString()} 描画`,
} as const;

export const SESSION_TEXT = {
  title: "ローカルセッション",
  description: "セッションを選択しただけでは、現在読込まれている走行データは切り替わりません。",
  refresh: "更新",
  refreshing: "更新中...",
  showIgnored: "除外済みも表示",
  clear: "表示を消去",
  listLabel: "ローカル走行セッション",
  noSessions: "ローカルセッションが見つかりません。",
  serviceUnavailable: "ローカルセッションサービスを利用できません。",
  loadingProjectedLap: "走行データを読込中...",
  failedLoadProjectedLap: "処理済み走行データの読込みに失敗しました。",
  processing: "処理中...",
  failedProcess: "選択したセッションの処理に失敗しました。",
  unknownVehicle: "車両不明",
  packets: "パケット",
  processAndLoad: "処理と読込",
  load: "読込",
  loading: "読込中...",
  actionReady: "処理済みデータをブラウザへ読込めます。",
  actionProcess: "この完了済みセッションは処理して読込めます。",
  actionPartial: "部分的な処理結果です。読込む前にCLIでの確認が必要です。",
  actionIgnored: "除外済みセッションはブラウザから処理できません。",
  actionIncomplete: "未完了の記録はまだ処理できません。",
  actionInvalid: "セッションの入力ファイルが無効です。",
  actionUnavailable: "このセッションに対してブラウザから実行できる操作はありません。",
  unknownStart: "開始時刻不明",
  unknownDuration: "記録時間不明",
  started: "開始時刻",
  trashTitle: "Windowsごみ箱",
  trashAction: "ごみ箱へ移動",
  trashCancel: "キャンセル",
  trashMoving: "移動中...",
  trashProgress: "セッションをWindowsのごみ箱へ移動中...",
  trashMoved: (sessionId: string) => `セッション ${sessionId} をWindowsのごみ箱へ移動しました。`,
  trashFailed: "セッションをごみ箱へ移動できませんでした。",
  trashConfirm: "このセッションをWindowsのごみ箱へ移動しますか？",
  trashHelp: "処理済みデータは対象外です。ごみ箱から復元できます。",
  busy: "別のセッション操作を実行中です。",
  loadedCannotTrash: "読込中のセッションはWindowsのごみ箱へ移動できません。",
  processedProtected: "処理済みセッションはこの操作から保護されています。",
  partialTrashBlocked: "部分的な処理結果です。この操作の前にCLIでの確認が必要です。",
  trashEligible: "対象のソースセッションをWindowsのごみ箱へ移動できます。",
} as const;

export const SESSION_STATUS_LABELS: Record<string, string> = {
  completed: "完了",
  "legacy-ready": "旧形式・処理可能",
  incomplete: "未完了",
  invalid: "無効",
  processed: "処理済み",
  unprocessed: "未処理",
  partial: "部分出力",
  ignored: "除外済み",
  loaded: "読込中",
};

export const CHART_TEXT = {
  title: "テレメトリーチャート",
  empty: "処理済み走行データを読込むとチャートを表示できます。",
  unknownSession: "セッション不明",
  rangeLabel: "チャート表示範囲",
  fullLap: "全周",
  selectedSection: "選択セクション",
  clearCursor: "カーソルを解除",
  cursorHelp: "チャート上にポインターを移動すると、距離、セクション、ラップタイム、各値を確認できます。",
  description: "有効走行ラインには置換されていないサンプルを使用します。巻き戻しはイベントマーカーとして残ります。間引きは表示専用で、極値を保持します。",
  distance: "距離",
  section: "セクション",
  lapTime: "ラップタイム",
  unavailable: "利用不可",
  notAvailable: "利用できません。セッションを再処理してください。",
  telemetryChartSuffix: "テレメトリーチャート",
} as const;

export const TUNE_TEXT = {
  title: "車両・チューニング",
  description: "必要最小限の車両情報です。エンジンの詳細はメモ欄へ自由入力します。",
  saveJson: "JSONを保存",
  loadJson: "JSONを読込む",
  ready: "準備完了",
  saved: "JSONを保存しました",
  loadFailed: "JSONを読込めませんでした",
  vehicleChangedTitle: "車両が変更されました",
  vehicleChangedBody: "読込んだテレメトリーは現在のチューニングとは別の車両です。現在入力されている車両情報とチューニング設定をリセットしますか？",
  currentTuneVehicle: "現在の設定",
  loadedTelemetryVehicle: "読込んだ車両",
  resetForLoadedVehicle: "リセットして切り替える",
  keepCurrentTune: "現在の設定を保持",
  vehicleMismatchWarning: "読込まれているテレメトリーの車両と、現在のチューニング設定の車両が一致していません。",
  vehicleIdentityIndeterminateWarning: "読込まれているテレメトリーの車両と現在のチューニング設定を比較できませんでした。現在の設定を保持しています。",
  unknownVehicle: "車両不明",
  vehicle: "車両",
  vehicleName: "車両名",
  year: "年式",
  class: "クラス",
  pi: "PI",
  drivetrain: "駆動方式",
  drivetrainUnset: "未設定",
  power: "出力",
  torque: "トルク",
  weight: "重量",
  frontWeight: "前輪荷重配分",
  engineNotes: "エンジンメモ",
  tires: "1. タイヤ空気圧",
  frontPressure: "フロント",
  rearPressure: "リア",
  gearing: "2. ギア",
  finalDrive: "ファイナルドライブ",
  alignment: "3. アライメント",
  frontCamber: "フロント",
  rearCamber: "リア",
  frontToe: "フロントトー",
  rearToe: "リアトー",
  frontCaster: "フロントキャスター",
  antiRollBars: "4. スタビライザー",
  springs: "5. スプリング",
  rideHeight: "6. 車高",
  damping: "7. ダンピング",
  frontRebound: "フロント減衰力",
  rearRebound: "リア減衰力",
  frontBump: "フロントバンプ",
  rearBump: "リアバンプ",
  aero: "8. エアロ",
  brakes: "9. ブレーキ",
  balance: "バランス",
  pressure: "圧力",
  differential: "10. デファレンシャル",
  differentialUnsetHelp: "駆動方式を選択すると、デフ設定項目が表示されます。",
  frontAccel: "フロント加速",
  frontDecel: "フロント減速",
  rearAccel: "リア加速",
  rearDecel: "リア減速",
  centerBalance: "センターバランス",
  front: "フロント",
  rear: "リア",
} as const;
